name: Deploy Task-3 Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repo
      - uses: actions/checkout@v3

      # Step 2: Deploy your Task-3 folder to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./aryananda.ps@mulearn/Task-3  
